name: CD

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed
    branches:
      - main

jobs:
  publish:
    name: Publish on Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - run: docker image build -t gabrielrufino/strabot-manager:latest -t gabrielrufino/strabot-manager:$(npm pkg get version | sed 's/"//g') .
      - run: docker login -u gabrielrufino -p ${{ secrets.DOCKER_HUB_TOKEN }}
      - run: docker image push -a gabrielrufino/strabot-manager
      - uses: peter-evans/dockerhub-description@v3
        with:
          username: gabrielrufino
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          repository: gabrielrufino/strabot-manager
